puts "The students of my cohort at Makers Academy"
puts "------------------"
puts "Dave - golf"
puts "Eddie - rock climbing"
puts "Catharina - travelling"
puts "Igor - making music"
puts "Marco - surfing"
puts "Lisa - swimming"
puts "Michiel - listening to music"
puts "Jean - movies"
puts "Nicola - running"
puts "Jennie - travelling"
puts "Iona - opera singing whilst boxing"
puts "Nikesh - loads of shit"
puts "Chloe - yoga"
puts "Toan - snowboarding"
puts "Jamie - football"
puts "Peter - cycling"
puts "Talal - swimming"
puts "Charlie - guitar"
puts "Charlotte - squash"
puts "Thomas - running"
puts "Zoe - origami"
puts "Hannah - mountaineering"
puts "Joe - dog walking"
puts "Alex - music"
puts "Jeremy - not being here"
print "We have 25 great students (by our count)"